### ISSUE TITLE
Issues with assertions and pageObjects.

### ISSUE THREAD

**Issue by drptbl** [maxgalbu/nightwatch-custom-commands-assertions#12]
Hello, today I've wanted to use pageObjects with `.assert.elHasChildren` command. It works without pageobjects, but when I try to combine it with pageObjects (I do this good way), I'm getting this error in console:

```
Running:  Solutions page tests should check that articles list contains childs (articles)
Error while running execute command: Converting circular structure to JSON
    at command (/x/assertions/elHasChildren.js:73:21)
    at module.exports.BaseAssertion._scheduleAssertion (/usr/local/lib/node_modules/nightwatch/lib/core/assertion.js:86:17)
    at module.exports.BaseAssertion._executeCommand (/usr/local/lib/node_modules/nightwatch/lib/core/assertion.js:81:17)
    at AssertionInstance.commandFn [as _commandFn] (/usr/local/lib/node_modules/nightwatch/lib/core/assertion.js:163:21)
    at AsyncTree.runCommand (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:157:30)
    at AsyncTree.runChildNode (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:117:8)
    at AsyncTree.walkDown (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:83:10)
    at AsyncTree.walkUp (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:100:8)
    at AsyncTree.walkDown (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:93:12)
    at AsyncTree.traverse (/usr/local/lib/node_modules/nightwatch/lib/core/queue.js:71:10)
```

Any ideas? Would love to hear!

**Comment by maxgalbu** [comment]
It works for me, see this test:

https://github.com/maxgalbu/nightwatch-custom-commands-assertions/blob/1bf1389f5e7f2e11570fdd84f80c62a6246ec63a/tests/runTests.js#L12

Can you share your code?

**Comment by maxgalbu** [comment]
This is the same issue as this: https://github.com/maxgalbu/nightwatch-custom-commands-assertions/issues/11 (problems with sections)
