### ISSUE TITLE
waitForDocumentLoaded() throws an error

### ISSUE THREAD

**Issue by johnringler** [maxgalbu/nightwatch-custom-commands-assertions#33]
I was really interested in using this custom command waitForDocumentLoaded() to speed up my tests.
However, it throws an error:

```
Error while running "execute" command: _this2.client.assertion is not a function
       TypeError: Error while running "execute" command: _this2.client.assertion is not a function
 at /project_path/node_modules/nightwatch-custom-commands-assertions/js/commands/waitForDocumentLoaded.js:76:31
           at NightwatchAPI.<anonymous> (/project_path/node_modules/nightwatch-custom-commands-assertions/js/commands/waitForDocumentLoaded.js:90:28)
           at Function.makePromise (/project_path/node_modules/nightwatch/lib/utils/index.js:128:28)
           at method.then (/project_path/node_modules/nightwatch/lib/index.js:130:62)
           at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I just the waitForDocumentLoaded test from your module (nom run test), I also get the same error.

**Comment by pac-nvalenzuela** [comment]
I updated `_this2.client.assertion` to `_this2.api.assert.ok`
